### PR TITLE
Adding KAT-7 and MeerKAT observatories

### PR DESCRIPTION
**Pull request by mserylak**
@scottransom I would like to ask you to add KAT-7 and MeerKAT as new observatories. Both sites have already been added into SIGPROC. I am waiting for tempo/tempo2 to accept my pull requests as well.

### CODE REVIEW

**Comment by scottransom** [comment]
Sorry about the delay, @mserylak!  Have you looked into getting "m" and "k" into TEMPO's obsys.dat file officially?  That is necessary or this stuff won't work properly.  I'd recommend asking David Nice or @demorest

**Comment by demorest** [comment]
'm' and 'k' are currently unused in the standard tempo distribution.  In tempo2 those codes are used for some of the MERLIN antennas.  This will probably be OK as long as you are careful about how you make TOAs (in short, try to use only tempo2-format TOAs with the appropriate two-char telescope code).

**Comment by mserylak** [comment]
Yes, I asked Mike Keith to add MeerKAT and KAT-7 to tempo2 and he agreed to do it. As for the tempo I sent some mails around asking for the same but I have not heard back (must have written to the wrong people). We are in commissioning phase of MeerKAT (and using KAT-7 for comparison) so adding those two to tempo would help us.

**Comment by scottransom** [comment]
Well given what @demorest said about "m" and "k" in TEMPO, if you could send him appropriate obsys.dat lines, I'm sure that he could push that in.  So I'd recommend that.  I'll merge this pull request now, though.

**Pull request merged**
