### PR TITLE
Move python code to module, issue #69. 

### PR DESCRIPTION
**Pull request by gijzelaerr**
Based on the python3 branch. This became quite a rigorous PR, I hope it gets accepted. I think most of the changes are essential to make sure presto is ready for the future. Let me know if you have any questions or want to see things differently.

changes:
 * Move all python code to a presto module
 * moved python files from `lib/python` to `python/presto`
 * Moved existing C modules into `presto` module
 * Improve the setup.py script, less need for `PRESTO` or `PGPLOT_DIR` variable on a generic system 
 * install all scripts in `bin/` by `setup.py`
 * Change internals to import presto code from presto module
 * Cleanup imports, remove unused imports
 * Improve python3 compatibility
 * Solve some bugs (missing variables, typos)
 * marked bugs (search for todo)
 * Drop pyfits requirement, replace by astropy
 * replace `cosine_rand.pickle` with `cosine_rand.json` (easier for py3 compat)
 * improve pep8 validation
 * Replacing tabs with spaces
 * Replace `\u` with `\\u` since it has the same effect and is py3 compatible
 * build fftfit using setup.py so no need for the Makefile anymore.

### CODE REVIEW

**Comment by scottransom** [comment]
@gijzelaerr This is looking great!  Thanks so much for the patches!  I've been pretty swamped the last few days, but hope to get this all into a merge-able state within the next couple weeks.

**Comment by paulray** [comment]
What is the status on this?  Is this likely to get merged sometime soon?  I'll likely change my default python to 3.6 whenever that happens.

**Comment by gijzelaerr** [comment]
Let me know if there is anything I can do to help merge this PR.

**Comment by scottransom** [comment]
@gijzelaerr  I'm back working on this and from a clean install, I'm getting a failure because pyslalib is trying to be auto-installed and that is failing.  Are you seeing that?

**Comment by gijzelaerr** [comment]
i'm unable to verify soon, but i'll do when I can. What is the issue? Otherwise open an issue for that.

Maybe a good plan to enable continues integration to this project. There are no unit tests as far as I know, but just hcecking if the project installs for both py2 and py3 would already be a great test. I can do a pull request with some docker files for travis, if you enable travis for this project. I've done the same for casacore and other projects: https://travis-ci.org/casacore/casacore

**Comment by scottransom** [comment]
I would love to eventually get PRESTO working with travis.  But writing the unit tests will take some time -- I already have some tests that I run when I install on a new machine, and I have made some python tests (which test quite a bit of the C code as well as the python) in tests/test_presto_python.py.

I'm getting failures of a bunch of things now, though, just given the new install locations.  So I will have to go through a bunch manual testing to find those before we merge this.

Anyway, I like the idea of installing the python code "properly", it is just making the porting take more time (and it will break people's code also, which stinks).

**Comment by paulray** [comment]
This is just part of the pain we are all going to have to go through to switch to Python 3, so clearly now is the right time.

**Comment by gijzelaerr** [comment]
I experience no problems pip installing presto and its dependencies. slalib installs succesfully from pip and the KERN package. What is the error you are seeing? 

About unittests, you dont need unittest to test the compilation/installation on travis. This would already be an important check. I'll add some docker files and a travis file that will compile and install for python2 and python3 and do a pep8 style check.

About breaking the code, that is why i proposed making a release before doing this refactor, then we have more freedom to do a rewrite and cleanup. If things break for people they can go back to that previous release.

**Comment by gijzelaerr** [comment]
done! I also added a `mypy` job. since it detects so many issues it is allowed to fail together with `pep8`.

**Comment by matteobachetti** [comment]
Hi @gijzelaerr, If I try to install it on a Mac with `pip install .` or `python setup.py install`, I get some errors related to deprecated Numpy API. Is this masking something else? Are there specific installation instructions for this new version (e.g. unlisted dependencies etc.)?

**Comment by gijzelaerr** [comment]
meanwhile, this branch has not been merged and the master branch is diverging in the meantime, making it even more unlikely to get this merged.

Currently, what is the biggest show stopper to proceed to merge this PR?

**Comment by scottransom** [comment]
@gijzelaerr Just my time to test all the many parts.  It is a big priority for me to get it done this summer.  And I'm planning on rebasing it to help with the stuff that has diverged.  I'm traveling for the next ~10 days, but late June/early July it will get some effort.  There are a couple good collaborators of mine who are switching to python3, so it really needs to happen.  And I definitely appreciate the work that you have done.  Thanks!

**Comment by gijzelaerr** [comment]
ok lets hope for the best

**Comment by matteobachetti** [comment]
Hi @gijzelaerr I'm trying again to install presto under python 3.7.
I'm basically just building with  `python setup.py install`. Is that correct?
The compilation runs fine provided that I install SLALIB with pip _before_ that.

Then, when I start using it, I have the following situation:
+ none of the c-compiled executables show up in the PATH (e.g. prepfold, accelsearch)
+ many Python scripts get built (they appear in the `build/`tree) but do not get copied to somewhere in the PATH, others do (e.g. `get_TOAs.py` does, `prepfold.py` doesn't)
+ If I run ipython and `import presto.presto`, I get
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/virtualenvs/py37/lib/python3.7/site-packages/presto-2.2-py3.7-linux-x86_64.egg/presto/presto/prestoswig.py in swig_import_helper()
     14         try:
---> 15             return importlib.import_module(mname)
     16         except ImportError:

/usr/lib/python3.7/importlib/__init__.py in import_module(name, package)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 

/usr/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'presto.presto._presto'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-f49361537f9b> in <module>
----> 1 import presto.presto

~/virtualenvs/py37/lib/python3.7/site-packages/presto-2.2-py3.7-linux-x86_64.egg/presto/presto/__init__.py in <module>
      3 from builtins import input
      4 from builtins import range
----> 5 from .prestoswig import *
      6 import os.path
      7 import numpy as np

~/virtualenvs/py37/lib/python3.7/site-packages/presto-2.2-py3.7-linux-x86_64.egg/presto/presto/prestoswig.py in <module>
     16         except ImportError:
     17             return importlib.import_module('_presto')
---> 18     _presto = swig_import_helper()
     19     del swig_import_helper
     20 elif _swig_python_version_info >= (2, 6, 0):

~/virtualenvs/py37/lib/python3.7/site-packages/presto-2.2-py3.7-linux-x86_64.egg/presto/presto/prestoswig.py in swig_import_helper()
     15             return importlib.import_module(mname)
     16         except ImportError:
---> 17             return importlib.import_module('_presto')
     18     _presto = swig_import_helper()
     19     del swig_import_helper

/usr/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

ImportError: /home/mbachett/virtualenvs/py37/lib/python3.7/site-packages/presto-2.2-py3.7-linux-x86_64.egg/_presto.cpython-37m-x86_64-linux-gnu.so: undefined symbol: is_power_of_10

```

Am I doing something wrong?
Thanks in advance

**Comment by gijzelaerr** [comment]
hi @matteobachetti . Does your PR to my PR fix your issues?

**Comment by matteobachetti** [comment]
Hi @gijzelaerr no, it just fixes the current merge conflicts.

**Comment by gijzelaerr** [comment]
ok. I'm not completely sure what is causing your errors. It has been a long time ago by now, but as far as I know, the refactor mostly worked. I'm a contractor who did this work in a code improvement sprint last year. Unfortunately, I ran out of budget and time to work on astronomy software so I don't really have much time to investigate this much further. I can answer short questions and think with you though.

**Comment by matteobachetti** [comment]
@gijzelaerr oh, I see. Thanks for your work, I'll try to figure out what is going on.

**Comment by scottransom** [comment]
Closing this because I finally merged #106

**Pull request closed without merging**
