### PR TITLE
Do not read in padding from end of timeseries in single_pulse_search.py

### PR DESCRIPTION
**Pull request by pscholz**
Hi Scott,

I've made a small modification to single_pulse_search.py to ignore the padding when reading in timeseries. I've tested it and it seems to work well.

Paul

### CODE REVIEW

**Comment by scottransom** [comment]
Hmmm.  I forgot that the code was already handling padding within the file.  So why wasn't it handling padding at the end properly?  Padding at the end was definitely listed in the "offregions".

**Comment by pscholz** [comment]
The prune_border_cases function was just rejecting events that were within
half a bin width of the beginning of the padding, which is not enough since
the padding will throw off the statistics in all the "chunks" that include
some of it. I think that not reading in the padding in the first place is
an easier, more robust solution.

**Comment by scottransom** [comment]
Yeah, but that's my exact point.  If what you say is true, it is a bug in prune_border_cases.  That is what should be fixed, not hack to work around part of a bug....

**Comment by scottransom** [comment]
Although I agree that if the end of the file is all padding, it doesn't make sense to read it in and search it.

**Comment by scottransom** [comment]
BTW, the patch also has a problem.  If offregions doesn't exist, python will throw an exception.  That needs to be indented under if info.breaks:

**Comment by pscholz** [comment]
prune_border_cases removes events after they are identifed. The problem is
that the search is using some of the padding to calculate statistics, which
is causing fake events to be found that come significantly before the
padding starts. So its not really a bug with prune_border_cases, its that
pruning the cand events after searching is not the right solution, since
the problem is caused by the running std deviation being calculated using
the padding data during searching.

**Comment by scottransom** [comment]
Yeah, true.  But I don't think this is the whole story.  It is possible (actually likely) that there will be padded parts of the data that we don't know about (because of application of a full-bandwidth mask over some time interval) which will cause the stdev to be artificially too low.  Note that this could even be happening with some of the PALFA observations.  I think a better solution would be to somehow identify those regions and ignore candidates within them (note that this is what bad blocks is for).

**Comment by pscholz** [comment]
Ok. As you say, bad block removal identifies chunks with high or low std
dev, and ignores them in the search, which is exactly what we want. So
should we revisit our decision to turn off bad block removal when using
zerodming in PALFA? Or is there a way to better identify those regions that
would throw away less data than bad block removal?

**Comment by pscholz** [comment]
Ok. I've indented it under "if info.breaks:". So it we do go forward with this patch, that's fixed.

**Pull request merged**
