### PR TITLE
Move and fix example python scripts in python3 branch

### PR DESCRIPTION
**Pull request by paulray**
Minor fix to see if I can do a PR to a PR.

### CODE REVIEW

**Comment by paulray** [comment]
OK, I moved what I thought made sense into $PRESTO/examplescripts

I am finding a segfault in ffdot_example.py that is not totally repeatable.   It is happening on this line:
```python
ppgplot.pgmtxt("B", 2.4, 0.5, 0.5, "Relative Power");
```
But when I tried a script to isolate that I can't reproduce the segfault, so something else must be overwriting memory. Not sure what is going on there.

**Comment by scottransom** [comment]
Hmmm.  Interesting.  Note that I made changes to ACCEL_sift.py today so we now have conflicts.  I'm actually not sure the best way to resolve that!

**Comment by paulray** [comment]
I didn't change ACCEL_sift.py except to move it, so you can just resolve by choosing your version.
Maybe merge the PR?

**Comment by paulray** [comment]
Actually, I just realized that I could pull your branch and merge it into mine, so my PR now incorporates all your changes. At least I think that is true.

**Comment by paulray** [comment]
Note, the segfaults I get on my laptop for ffdot_example.py and jerk_example.py do not occur on my desktop, so they must be highly system dependent, as memory overwriting bugs usually are.

If you can merge this branch that would be good, to prevent more conflicts from arising.

**Comment by scottransom** [comment]
@paulray  Thanks for this!  I'll try any merge this today.

**Pull request merged**
