### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by scottransom**
This encompases #90 and #94 (rebased on #90) and was rebased on master.  This will be the base of the new PRESTO 3.0

### CODE REVIEW

**Comment by scottransom** [comment]
@gijzelaerr So the compiled C parts of the presto.presto build were broken because the resuting _presto.so shared lib wasn't linked to the real libpresto.so library that is built by the Makefile in $PRESTO/src.  Do you know where/how in the travis+docker build scheme we would set the PRESTO and LD_LIBRARY_PATH environment variables and cd to src and "make"?

BTW:  Thank you (and @matteobachetti) *sooo* much for all the effort that you put into this pull request.  I did a ton of testing today and am amazed at how much of it works (I did have to fix a buch of bugs, but it wasn't bad at all -- and I'm sure that many more are lurking.  But *thank you*!!

**Comment by gijzelaerr** [comment]
for example for py3 probably just after this line:

https://github.com/gijzelaerr/presto/blob/move_to_module/.travis/py3.docker#L16

`ADD . /code` copies the source into the container
`ENV PRESTO /code` # will set the environment variable to `/code`
`WORKDIR /code/src`
`RUN make`
etc

I guess. :)

**Comment by gijzelaerr** [comment]
for the future I recommend using one buildsystem, although i'm not sure if you can produce binaries using setuptools.

**Comment by gijzelaerr** [comment]
BTW, just to give the (financial) credits, this work was done in about 1.5 day while being paid by SETI Berkeley https://seti.berkeley.edu/

If you are in need of future improvements I'm available for contracting work.

good luck.

**Comment by matteobachetti** [comment]
Hey @scottransom, I was wondering: are there any changes in the installation instructions in this new version? If so, I think it would help to have them written down, so that more people can install easily, test and chime in with possible bugs.

**Comment by scottransom** [comment]
@matteobachetti Yes, there will definitely be changes in the installation instructions -- although not dramatic ones.

Basically, you do not need $PRESTO/lib/python in PYTHONPATH anymore (and should not have it there), you compile the C parts of PRESTO as per usual, and then do a "pip install ." or "python setup.py install" from the top directory.  All of the python stuff gets installed where it normally would go for any other python module.

I will update the README about this as well.

**Comment by paulray** [comment]
So, if we want to try this, should we try using the python3 branch? Or is it not ready for beta testing?

**Comment by scottransom** [comment]
@paulray You should definitely try it.  I have now successfully gone through the full PRESTO tutorial (plus making and using TOAs and gaussian fitting and viewing residuals and fitting orbits) with it using Python3 and I think it is working.

However, I might have screwed up something in a recent rebase that had to do with Python2 compatability....  So I will test that a bit over the weekend.

But if that goes well, this is getting merged soon.  Your testing would be much appreciated!

**Comment by paulray** [comment]
Will do.  I'll also say that this PR would be a good opportunity to get rid of the fortran version of FFTFIT and lose the dependence on fortran.

**Comment by scottransom** [comment]
@paulray Not sure that getting rid of fftfit will get rid of a fortran dependence as PGPLOT is a fortran library and demands linking to the main fortran library.  But I agree with the general sentiment.  I think that there is a python replacement for it in stingray...  Maybe @matteobachetti knows and can comment?

**Comment by scottransom** [comment]
@paulray Note that there are also a couple other fortran source files in PRESTO itself (and, as I mentioned before, things need to be linked by gfortran given PGPLOT).  So I'm not sure that it is really worth getting rid of FFTFIT right now for that reason.  And getting rid of *all* the fortran in PRESTO would be a lot more work (plus it needs TEMPO which is fortran as well!).  Long live Fortran!

**Comment by paulray** [comment]
OK, that's all true, but PINT is 100% python, except for the dependence on FFTFIT, so it will still be good to get the python version in there.

**Comment by paulray** [comment]
It looks like `from presto import presto` fails.

I found this when I did `import presto.pypsrcat as cat`

Here is the exception:
```
In [7]: import presto.pypsrcat as cat 
   ...:  
   ...:                                                                                                                                                                     
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/Library/Python/3.6/lib/python/site-packages/presto-2.2-py3.6-macosx-10.11-x86_64.egg/presto/presto/prestoswig.py in swig_import_helper()
     14         try:
---> 15             return importlib.import_module(mname)
     16         except ImportError:

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'presto.presto._presto'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-7-8720f6f80813> in <module>
----> 1 import presto.pypsrcat as cat
      2 

~/Library/Python/3.6/lib/python/site-packages/presto-2.2-py3.6-macosx-10.11-x86_64.egg/presto/pypsrcat.py in <module>
      8 import astropy.coordinates as c
      9 import astropy.units as u
---> 10 from presto import presto, psr_utils
     11 
     12 ## The most recent catalogs are available here:

~/Library/Python/3.6/lib/python/site-packages/presto-2.2-py3.6-macosx-10.11-x86_64.egg/presto/presto/__init__.py in <module>
      3 from builtins import input
      4 from builtins import range
----> 5 from .prestoswig import *
      6 import os.path
      7 import numpy as np

~/Library/Python/3.6/lib/python/site-packages/presto-2.2-py3.6-macosx-10.11-x86_64.egg/presto/presto/prestoswig.py in <module>
     16         except ImportError:
     17             return importlib.import_module('_presto')
---> 18     _presto = swig_import_helper()
     19     del swig_import_helper
     20 elif _swig_python_version_info >= (2, 6, 0):

~/Library/Python/3.6/lib/python/site-packages/presto-2.2-py3.6-macosx-10.11-x86_64.egg/presto/presto/prestoswig.py in swig_import_helper()
     15             return importlib.import_module(mname)
     16         except ImportError:
---> 17             return importlib.import_module('_presto')
     18     _presto = swig_import_helper()
     19     del swig_import_helper

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

ImportError: dlopen(/Users/paulr/Library/Python/3.6/lib/python/site-packages/presto-2.2-py3.6-macosx-10.11-x86_64.egg/_presto.cpython-36m-darwin.so, 2): Symbol not found: _choose_good_N
  Referenced from: /Users/paulr/Library/Python/3.6/lib/python/site-packages/presto-2.2-py3.6-macosx-10.11-x86_64.egg/_presto.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/paulr/Library/Python/3.6/lib/python/site-packages/presto-2.2-py3.6-macosx-10.11-x86_64.egg/_presto.cpython-36m-darwin.so
```

**Comment by matteobachetti** [comment]
@scottransom @paulray the code is in Stingray, I'm not satisfied with the error calculation but the fit itself works decently. I haven't had the time to make a PR to PINT as I had proposed in https://github.com/nanograv/PINT/issues/23. I wanted to change the interface so that it mimicked the PRESTO version. It shouldn't take long, I just haven't had the time to sit and do it -.-

**Comment by scottransom** [comment]
@paulray It can't find a symbol in the included library it doesn't seem like (and that would be libpresto.so).   Is your PRESTO and LD_LIBRARY_PATH variables set?  And does libpresto.so (or Mac equiv) exist in LD_LIBRARY_PATH?

**Comment by paulray** [comment]
OK, I got it to work. I had to delete my whole presto and checkout from scratch. I think some old binaries didn't get cleaned out by make clean and such.

On a different note, Python executables should not be in $PRESTO/python. If they are then when they try to import presto.XXX it looks in the "presto" subdir of $PRESTO/python instead of in the installed presto package.

So, for example, ppdot_plane_plot.py should be moved to $PRESTO/bin, and it also needs a patch:
```
--- a/python/ppdot_plane_plot.py
+++ b/python/ppdot_plane_plot.py
@@ -1,8 +1,8 @@
 from __future__ import print_function
 from builtins import zip
 import numpy as np
-import psr_utils as pu
-import pypsrcat as cat
+import presto.psr_utils as pu
+import presto.pypsrcat as cat
 import matplotlib.pyplot as plt
```

**Comment by paulray** [comment]
Is it possible for me to make PRs to your PR?

**Comment by scottransom** [comment]
@paulray I don't know!  You should try.

**Comment by gijzelaerr** [comment]
yes you can :)

**Comment by scottransom** [comment]
@paulray Thanks for the efforts!

Re the python executables, in general, I agree.  But there are several that are only for demonstration purposes -- like the P-Pdot one you mention.  And those I do not want to get installed.  I create an "examples" directory or "scripts" directory and move some of the code there that may help a user but that we wouldn't ordinarily like to have actually installed.

**Comment by paulray** [comment]
Sure, putting those kids of scripts into "examples" or something is a good plan.  They definitely don't work right where they are at the moment.

**Comment by gijzelaerr** [comment]
maybe at some point you should just merge these changes to master? That way you can structure issues easier in seperate branches and PRs :)

**Comment by scottransom** [comment]
@gijzelaerr It will be merged by the end of the week.  I couldn't merge things earlier because almost everything python related was broken -- and most people who use PRESTO simply use the latest commit from the master branch.  I've done a ton of tests and fixes over the past couple weeks and it is almost there.

**Comment by gijzelaerr** [comment]
ok, awesome. Sorry for breaking things, I thought I left it in a working state :) 

The argument that we can't change things in master since users will complain is something I hear quite often in scientific software projects. I think the reason people are using master is a lack of a regular release. You can probably save yourself quite some time if you try to let your presto community help you out maintain and improve presto by having a regular release cycle, encourage the creation of PRs and delegate certain tasks.

Anyway, I understand that your time is also limited and although I don't use your software personally I want to thank you also for making this software public and spending time and energy in maintaining this product.  Unfortunately, my time is also finite, but I don't mind spending a bit of time here and there improving presto where possible.

I'm very glad this PR finally got merged and I hope the quality of presto will keep on improving.

thanks again!

**Pull request merged**
