### PR TITLE
[WIP] Allow Python 3

### PR DESCRIPTION
**Pull request by matteobachetti**
This is a work-in-progress porting of all python code to python 3. Up to this stage, everything should keep working fine in Python 2, and something is still broken in Python 3.
Things to do:
- [ ] Check which divisions need to be converted to integer divisions, and which do not
- [ ] Check if there is any clash related to Unicode strings/bytes
- [x] Use the correct syntax in C code (e.g. change all `Py_Initmodule`s to the current syntax, `PyString_FromString`s to `PyBytes_FromString`s etc.)

### CODE REVIEW

**Comment by matteobachetti** [comment]
Update: the code now compiles correctly and I could execute `get_TOAs.py -h` without crashes on python 3

**Comment by matteobachetti** [comment]
Update: `get_TOAs.py` now correctly calculates TOAs in Python 3.

**Comment by matteobachetti** [comment]
@scottransom is there a specific set of tests that should be run? The ones in the "tests" directory don't seem to apply (very old compilers and libraries are used)

**Comment by scottransom** [comment]
@matteobachetti This looks great!  Thanks so much for working on this!

1. As for tests, yes, those are not good...  I should probably wipe that directory and start afresh. Having good test would be useful.  There really isn't anything good right now.  The best "tests" that I use right now are to make sure that fftfit works (the Makefile runs this automatically):
> python fftfit_src/test_fftfit.py
And then I run
> python ffdot_example.py
Those both exercise a lot of the tricky stuff.
Much more testing should be done...

2.  A student here @bandersen441 is resurrecting a stalled python wrapper update using Swig that I started a couple years ago.  Those wrappers have tests.  Of course all that was written for python 2.  I'm very interested in getting that code merged along with your python 3 updates.  You can see the branch on github, it is "swig_update".

3. Once the above is done, the next step will be to probably make it so that the PRESTO python code can be installed separately as per a "normal" python package.  There is an issue reported for that.  If you are interested in helping with that as well, that would be awesome!

Thanks again!

**Comment by matteobachetti** [comment]
@scottransom  I'm surely very interested in the wrapper and the packaging too. Do you think this PR needs major work? Having get_TOAs working in Py3 is of huge help for my daily routine at this moment :)

**Comment by scottransom** [comment]
@matteobachetti can youi run the two tests that I mentioned with your changes now?  And what about all of the *.py files in $PRESTO/bin/ ?  We don't want to break any of those -- some are used a lot (like single_pulse_search.py, DDplan.py, pygaussfit.py)  If your changes still allow those to work, then I think we might be able to merge fairly soon.

**Comment by matteobachetti** [comment]
Both `fftfit_test` and `ffdot_example` run in the system Python on my Ubuntu 16.04. (*)
For the rest of  the scripts, the only change should be an additional dependency (`six`), but everything *should* work as usual on Python 2.7. In all but `get_TOAs.py`, `fftfit` and dependencies, where I made all modifications that were needed for a full porting, I ran only the stage1 version of `futurize`, the safest. So, some of the things still might not work properly on Py3 but should definitely work on Py2. But of course I want to check it. I can run whatever works on `prepfold`'s products, like `pygaussfit` or `fitorb`. Can you provide small datasets to run `DDplan` et al.?

(*) For some reason, neither the stock and the new version of `ffdot_example` run on my Anaconda installation, even in Py2, due to a "double free or corruption", but I don't know why.

**Comment by matteobachetti** [comment]
@scottransom Update: while `test_fftfit.py` works in Python 3, I couldn't get `ffdot_example` to work. This is because of Py2-only machinery in the SWIG version used for the wrappers. It keeps working well on the systems' Python, anyway, it's not broken.

As for integrity checks:
`pygaussfit.py`, `fitorb.py`, `DDplan.py`,  keep working as usual. For the rest of the scripts:

+ Those that accept the `-h` script give the execution instructions correctly if called with `scriptname -h` 

+ For these and the others, I accept suggestion on how to test them more thoroughly.@scottransom Update: while `test_fftfit.py` works in Python 3, I couldn't get `ffdot_example` to work. This is because of Py2-only machinery in the SWIG version used for the wrappers. It keeps working well on the systems' Python, anyway, it's not broken.

As for integrity checks:
`pygaussfit.py`, `fitorb.py`, `DDplan.py`,  keep working as usual. For the rest of the scripts:

+ Those that accept the `-h` script give the execution instructions correctly if called with `scriptname -h`

**Comment by matteobachetti** [comment]
@scottransom I rebased to your `master` branch. I would propose to start merging the current modifications, and from now on remember about Python3 compatibility (e.g., using the new `print` function with `__future__`, etc.).
A guide for compatible Python coding: http://docs.astropy.org/en/stable/development/codeguide.html

**Comment by scottransom** [comment]
@matteobachetti This is excellent.  I will see if I can find some time tonight or tomorrow to check this out on my machine.  If it looks all good, I will merge it within the next couple days.  Thanks again!

**Comment by matteobachetti** [comment]
@scottransom any news?

**Comment by scottransom** [comment]
@matteobachetti Yeah...  we are working on testing it now with the big PALFA pipeline.  Want to make sure there are no hidden gotchas.

**Comment by matteobachetti** [comment]
@scottransom  After exactly one year, I was wondering what is the status of Python 3 support :)

**Comment by scottransom** [comment]
@matteobachetti So I'm finally ready to start working on making PRESTO fully Python3 compatible and would like to use some or all of your work to help make that happen.  Any idea how much work it would be to do a rebase on the current master?

**Comment by scottransom** [comment]
BTW, when I updated the Python v2 interface this past year, I make a new set of test functions in $PRESTO/tests/test_presto_python.py  It isn't in an official test format (need to do that), but it can be run using "python test_presto_python.py".  It checks a bunch of the presto module.

**Comment by matteobachetti** [comment]
Hey @scottransom I'm traveling these days, I'll try to make an estimate

**Comment by scottransom** [comment]
I'm giving it a try myself....  quite a few conflicts, but I can probably work through them

**Comment by scottransom** [comment]
See the new updated pull request #90 with the above conflicts resolved.  Closing and moving to the new python3new branch.

**Pull request closed without merging**
