### PR TITLE
Changed frequency labels to the double datatype to match current definit...

### PR DESCRIPTION
**Pull request by kstovall**
Changed the frequency labels to doubles in psrfits.c .

### CODE REVIEW

**Comment by scottransom** [comment]
@kstovall I just noticed this pull request from last year.  Is this still needed?  And is it the only change that you guys have found to be required for LWA data?

**Comment by paulray** [comment]
This is definitely needed.  The PSRFITS standard was modified to make the frequencies doubles as well.

**Comment by scottransom** [comment]
Done.  Thanks!

**Comment by kstovall** [comment]
Thanks for merging. There are a few other minor changes that I would like to see in PRESTO, but I need to take a look at them first. I will issue another pull request for those when I have checked them.

**Pull request merged**
