### PR TITLE
Merge in your $CLIPBINSFILE hack?

### PR DESCRIPTION
**Pull request by pscholz**
Hi Scott,

This is your patch to clipping.c where the user sets $CLIPBINSFILE to a file of timeseries bins to be clipped. In theory it has been running on Guillimin for the past year (but may not have been... we'll talk about this), so should probably be in PRESTO and not just running on Guillimin as a hack.

Paul

### CODE REVIEW

**Comment by scottransom** [comment]
Ah-ha....  I see why the whole file has been changed.  Your editor has changed all of the indenting to 3-spaces instead of 4 spaces, which is what is used in the rest of PRESTO.  I highly recommend setting 4-spaces to your default in your editor.  And to fix this pull request you can either have your editor do that, or you can use the "indent" command (often found on linux machines) with the following command line (it uses the very common K&R-style of indentation):   indent -kr -nut -l85 MYFILE.c

**Comment by scottransom** [comment]
Hmmm....  Maybe I'm wrong about this....  I'm checking into it now.

**Comment by scottransom** [comment]
Yeah, somehow some of the files that are in *my* PRESTO have gotten changed to 3-space indention!  That is despite the fact that my editor is set at 4-spaces!  Strange...

**Comment by pscholz** [comment]
Yeah. I was confused as to what was going on the whole file changing, since the file was from you, and presumably would have been written in the same way as the old file... but looks like you figured it out.

**Pull request merged**
